classDiagram
    direction TB
    class ICanvasTool {
        <<interface>>
        +onMouseDown/Move/Up() ToolResult
        +onClick/KeyDown() ToolResult
        +overlay() ToolOverlay
        +cancel() ToolResult
    }
    class CreationTool~T~ {
        #draft : T
        #beginDraft()
        #commitDraft() ToolResult
        #cancelDraft() ToolResult
    }
    class ShapeCreationTool~T~
    class DragTool~T~

    ICanvasTool <|.. SelectTool
    ICanvasTool <|.. TextTool
    ICanvasTool <|.. CreationTool~T~
    CreationTool~T~ <|-- ShapeCreationTool~T~
    ShapeCreationTool~T~ <|-- DragTool~T~
    ShapeCreationTool~T~ <|-- PointTool
    ShapeCreationTool~T~ <|-- PencilTool
    ShapeCreationTool~T~ <|-- PolygonTool
    DragTool~T~ <|-- LineTool
    DragTool~T~ <|-- RectangleTool
    DragTool~T~ <|-- EllipseTool
