flowchart LR
    W[Window / Element Tree] --> C[CanvasRenderer]

    C --> G[1. Grid]
    C --> S[2. Scene Objects]
    C --> D[3. Tool Draft]
    C --> O[4. Selection Overlay]

    S --> SR[SceneRenderer]
    SR --> SHR[ShapeRenderer]
    SR --> TR[TextRenderer]

    G --> GL[OpenGL]
    SHR --> GL
    TR --> GL
    %% D --> GL
    D --> SHR
    D --> TR
    O --> GL
