classDiagram
    class Application
    class Window
    class RootElement
    class EventTarget
    class Element
    class StackPanel
    class DockPanel
    class CanvasElement
    class TextElement
    class InputElement
    class Button
    class RenderContext

    Application "1" *-- "多個" Window : 擁有
    Window "1" *-- "1" RootElement : 擁有
    EventTarget <|-- Window
    EventTarget <|-- Element
    Element <|-- RootElement
    Element <|-- StackPanel
    Element <|-- DockPanel
    Element <|-- CanvasElement
    Element <|-- TextElement
    Element <|-- InputElement
    Element <|-- Button
    Element --> RenderContext : 繪製
